// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6cOB1HOzkstaSR6hGweFkuImNaD-Y1o4',
    appId: '1:183721943397:web:09dbc6334de419525c818c',
    messagingSenderId: '183721943397',
    projectId: 'ecommerce-b18a5',
    authDomain: 'ecommerce-b18a5.firebaseapp.com',
    storageBucket: 'ecommerce-b18a5.appspot.com',
    measurementId: 'G-L80TWH4E83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaCyB_he_h9whd2clIvc_MiTBGGpscj8Q',
    appId: '1:183721943397:android:dba7a8f9f97e048d5c818c',
    messagingSenderId: '183721943397',
    projectId: 'ecommerce-b18a5',
    storageBucket: 'ecommerce-b18a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzYhrmO0BRBChxoTMHYAGbB-IVtQwIAkw',
    appId: '1:183721943397:ios:3a6391552d279dd25c818c',
    messagingSenderId: '183721943397',
    projectId: 'ecommerce-b18a5',
    storageBucket: 'ecommerce-b18a5.appspot.com',
    iosBundleId: 'com.example.ecommerece',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzYhrmO0BRBChxoTMHYAGbB-IVtQwIAkw',
    appId: '1:183721943397:ios:6f7c7df9cf5b9e675c818c',
    messagingSenderId: '183721943397',
    projectId: 'ecommerce-b18a5',
    storageBucket: 'ecommerce-b18a5.appspot.com',
    iosBundleId: 'com.example.ecommerece.RunnerTests',
  );
}
